GET http://localhost:8001/params/17?nom=hola
Accept-Language: cristino
Accept: text/plain

###

GET http://localhost:8001/params/2?nom=adios
Accept-Language: es-es
Accept: text/xml

###

GET  http://localhost:8001/salida
Accept-Language: es-es
Accept: text/xml, application/json

###

POST http://localhost:8001/salida
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
  "id": 7,
  "nombre": "Nuevo",
  "apellidos": "Actooooooooooor"
}

###

POST http://localhost:8001/salida
Accept-Language: es-es
Accept: text/xml, application/json
Content-Type: application/xml

<ActorDTO>
  <id>0</id>
  <nombre>Pepito</nombre>
  <apellidos>Grillo</apellidos>
</ActorDTO>

###

POST http://localhost:8001/salida
Accept-Language: es-es
Accept: text/xml, application/json
Content-Type: application/x-www-form-urlencoded

id=0&nombre=Pepito&apellidos=Grillo


###
GET http://localhost:8010/categorias

###
GET http://localhost:8010/actores


###
GET http://localhost:8010/language

###
GET http://localhost:8010/peliculas/1/actores


###
POST http://localhost:8010/language/5
Content-Type: application/json

{
  "languageId": 5,
  "name": "Spanish",
}


###
POST http://localhost:8010/localhost:8010/peliculas
Content-Type: application/json
Accept: text/xml, application/json
{
  "id": 200,
  "titulo": "pelicula natalia",
  "descripcion": " descripcion pelicula",
  "length": 20,
  "clasificación": ,
  "año_lanzamiento": ,
  "duracion": ,
  "tasa_rendimiento": ,


}
