GET http://localhost:8001/params/17?nom=hola
Accept-Language: cristino
Accept: text/plain

###

GET http://localhost:8001/params/2?nom=adios
Accept-Language: es-es
Accept: text/xml

###

GET  http://localhost:8001/salida
Accept-Language: es-es
Accept: text/xml, application/json

###

POST http://localhost:8001/salida
Accept-Language: es-es
Accept: text/plain, application/json
Content-Type: application/json

{
  "id": 7,
  "nombre": "Nuevo",
  "apellidos": "Actooooooooooor"
}

###

POST http://localhost:8001/salida
Accept-Language: es-es
Accept: text/xml, application/json
Content-Type: application/xml

<ActorDTO>
  <id>0</id>
  <nombre>Pepito</nombre>
  <apellidos>Grillo</apellidos>
</ActorDTO>

###

POST http://localhost:8001/salida
Accept-Language: es-es
Accept: text/xml, application/json
Content-Type: application/x-www-form-urlencoded

id=0&nombre=Pepito&apellidos=Grillo


###
GET http://localhost:8010/categorias

###
GET http://localhost:8010/actores


###
GET http://localhost:8010/language

###
GET http://localhost:8010/peliculas/1001


###
POST http://localhost:8010/peliculas
Content-Type: application/json
Accept:  application/json

{
  "id": 0,
  "titulo": "pelicula natalia",
  "descripcion": "descripcion pelicula",
  "length": 20,
  "clasificación": "g",
  "año_lanzamiento":2021,
  "duracion":2,
  "tasa_rendimiento":0.99,
  "replacementCost":20.99,
  "language":1
}

###
PUT http://localhost:8010/categorias/16
Content-Type: application/json

{
"categoryId": 16, "name": "SERIE B"
}

###
POST http://localhost:8010/language/7
Content-Type: application/json

{ "idioma": "Español" }

###
POST http://localhost:8010/language/5
Content-Type: application/json

{
  "languageId": 5,
  "name": "Spanish",
}
